// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAymTziAepb6Pz2qqL_5TYGKmjvtZBkddg',
    appId: '1:605502669571:web:6e2243bea8fc3bde831f36',
    messagingSenderId: '605502669571',
    projectId: 'chatapp-22d54',
    authDomain: 'chatapp-22d54.firebaseapp.com',
    storageBucket: 'chatapp-22d54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQCyDnDWgwrs8Ww85xgH9kVOuXme11Zbo',
    appId: '1:605502669571:android:e6c0b2c0ba5e3c5a831f36',
    messagingSenderId: '605502669571',
    projectId: 'chatapp-22d54',
    storageBucket: 'chatapp-22d54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOEMKb4WICA3zYhW7um0tBUdXC8R9zQ04',
    appId: '1:605502669571:ios:6d4e0b1300ace123831f36',
    messagingSenderId: '605502669571',
    projectId: 'chatapp-22d54',
    storageBucket: 'chatapp-22d54.appspot.com',
    iosClientId:
        '605502669571-fundltmp9tkgoshooagf1ar9pjvdu36l.apps.googleusercontent.com',
    iosBundleId: 'com.example.firbase',
  );
}
